const CARDS_LIST = [
    {
        id: 1,
        vip: 0,
        age: 0,
        sex: 0,
        dt: 'Jan 30',
        short: 'Just friends at first ',
        from: 'LaGrange',
        img: 'c-img',
        title: 'Ms Exotic looking for an older gentleman to bring light into your life',
        desc: ` I'm slim but curvaceous, ambitious,and soft-hearted lady with a tropical, exotic flair. Moonlight, delicious food and shiny things bring out the best in me. I am shy but enjoy engaging in intelligent conversations in business or politics. Something many can attest to, is the radiance and glow that often follow me. I am a force to be reckoned with, but emit only positivity--something I'd love to see in the world. I am ambitious and I need to be- I've got a world to change.I can't wait to meet my next benefactor.<br><br>I am seeking an older gentleman. Someone honest, direct, and generous. I'd like to meet someone who is wise, generous and willing to share his wisdom. Let's start with a glass of wine at an upscale restaurant to unwind your day.<br><br>Looking for generous gentlemen that are ages 45+ and looking to mentor a young lady on a dinner date`,
        note: `* Please include a picture and your age *`
    },
    {
        id: 2,
        vip: 0,
        age: 0,
        sex: 0,
        dt: 'Jan 30',
        short: 'Is she right?',
        from: 'Auburn',
        img: 'c-img',
        title: 'Ms Exotic looking for an older gentleman to bring light into your life',
        desc: ` I'm slim but curvaceous, ambitious,and soft-hearted lady with a tropical, exotic flair. Moonlight, delicious food and shiny things bring out the best in me. I am shy but enjoy engaging in intelligent conversations in business or politics. Something many can attest to, is the radiance and glow that often follow me. I am a force to be reckoned with, but emit only positivity--something I'd love to see in the world. I am ambitious and I need to be- I've got a world to change.I can't wait to meet my next benefactor.<br><br>I am seeking an older gentleman. Someone honest, direct, and generous. I'd like to meet someone who is wise, generous and willing to share his wisdom. Let's start with a glass of wine at an upscale restaurant to unwind your day.<br><br>Looking for generous gentlemen that are ages 45+ and looking to mentor a young lady on a dinner date`,
        note: `* Please include a picture and your age *`
    },
    {
        id: 3,
        vip: 1,
        age: 0,
        sex: 0,
        dt: 'Jan 30',
        short: 'Looking for BBW',
        from: 'Auburn',
        img: 'c-img',
        title: 'Ms Exotic looking for an older gentleman to bring light into your life',
        desc: ` I'm slim but curvaceous, ambitious,and soft-hearted lady with a tropical, exotic flair. Moonlight, delicious food and shiny things bring out the best in me. I am shy but enjoy engaging in intelligent conversations in business or politics. Something many can attest to, is the radiance and glow that often follow me. I am a force to be reckoned with, but emit only positivity--something I'd love to see in the world. I am ambitious and I need to be- I've got a world to change.I can't wait to meet my next benefactor.<br><br>I am seeking an older gentleman. Someone honest, direct, and generous. I'd like to meet someone who is wise, generous and willing to share his wisdom. Let's start with a glass of wine at an upscale restaurant to unwind your day.<br><br>Looking for generous gentlemen that are ages 45+ and looking to mentor a young lady on a dinner date`,
        note: `* Please include a picture and your age *`
    },
    {
        id: 4,
        vip: 0,
        age: 0,
        sex: 0,
        dt: 'Jan 30',
        short: 'Businessman in town today and tomorrow',
        from: '',
        img: 'c-img',
        title: 'Ms Exotic looking for an older gentleman to bring light into your life',
        desc: ` I'm slim but curvaceous, ambitious,and soft-hearted lady with a tropical, exotic flair. Moonlight, delicious food and shiny things bring out the best in me. I am shy but enjoy engaging in intelligent conversations in business or politics. Something many can attest to, is the radiance and glow that often follow me. I am a force to be reckoned with, but emit only positivity--something I'd love to see in the world. I am ambitious and I need to be- I've got a world to change.I can't wait to meet my next benefactor.<br><br>I am seeking an older gentleman. Someone honest, direct, and generous. I'd like to meet someone who is wise, generous and willing to share his wisdom. Let's start with a glass of wine at an upscale restaurant to unwind your day.<br><br>Looking for generous gentlemen that are ages 45+ and looking to mentor a young lady on a dinner date`,
        note: `* Please include a picture and your age *`
    },
    {
        id: 5,
        vip: 2,
        age: 0,
        sex: 0,
        dt: 'Jan 29',
        short: 'Want to lick your  pussy  ',
        from: 'LaGrange',
        img: 'c-img',
        title: 'Ms Exotic looking for an older gentleman to bring light into your life',
        desc: ` I'm slim but curvaceous, ambitious,and soft-hearted lady with a tropical, exotic flair. Moonlight, delicious food and shiny things bring out the best in me. I am shy but enjoy engaging in intelligent conversations in business or politics. Something many can attest to, is the radiance and glow that often follow me. I am a force to be reckoned with, but emit only positivity--something I'd love to see in the world. I am ambitious and I need to be- I've got a world to change.I can't wait to meet my next benefactor.<br><br>I am seeking an older gentleman. Someone honest, direct, and generous. I'd like to meet someone who is wise, generous and willing to share his wisdom. Let's start with a glass of wine at an upscale restaurant to unwind your day.<br><br>Looking for generous gentlemen that are ages 45+ and looking to mentor a young lady on a dinner date`,
        note: `* Please include a picture and your age *`
    },
    {
        id: 6,
        vip: 0,
        age: 0,
        sex: 0,
        dt: 'Jan 29',
        short: 'Does Anyone Flirt  Anymore? ',
        from: '',
        img: 'c-img',
        title: 'Ms Exotic looking for an older gentleman to bring light into your life',
        desc: ` I'm slim but curvaceous, ambitious,and soft-hearted lady with a tropical, exotic flair. Moonlight, delicious food and shiny things bring out the best in me. I am shy but enjoy engaging in intelligent conversations in business or politics. Something many can attest to, is the radiance and glow that often follow me. I am a force to be reckoned with, but emit only positivity--something I'd love to see in the world. I am ambitious and I need to be- I've got a world to change.I can't wait to meet my next benefactor.<br><br>I am seeking an older gentleman. Someone honest, direct, and generous. I'd like to meet someone who is wise, generous and willing to share his wisdom. Let's start with a glass of wine at an upscale restaurant to unwind your day.<br><br>Looking for generous gentlemen that are ages 45+ and looking to mentor a young lady on a dinner date`,
        note: `* Please include a picture and your age *`
    },
    {
        id: 7,
        vip: 0,
        age: 0,
        sex: 0,
        dt: 'Jan 29',
        short: 'Hung 420 friendly  Asian guy :)',
        from: 'AU',
        img: 'c-img',
        title: 'Ms Exotic looking for an older gentleman to bring light into your life',
        desc: ` I'm slim but curvaceous, ambitious,and soft-hearted lady with a tropical, exotic flair. Moonlight, delicious food and shiny things bring out the best in me. I am shy but enjoy engaging in intelligent conversations in business or politics. Something many can attest to, is the radiance and glow that often follow me. I am a force to be reckoned with, but emit only positivity--something I'd love to see in the world. I am ambitious and I need to be- I've got a world to change.I can't wait to meet my next benefactor.<br><br>I am seeking an older gentleman. Someone honest, direct, and generous. I'd like to meet someone who is wise, generous and willing to share his wisdom. Let's start with a glass of wine at an upscale restaurant to unwind your day.<br><br>Looking for generous gentlemen that are ages 45+ and looking to mentor a young lady on a dinner date`,
        note: `* Please include a picture and your age *`
    },
    {
        id: 8,
        vip: 0,
        age: 0,
        sex: 0,
        dt: 'Jan 30',
        short: 'SWM49 seeks  SWF18-39 for LTR  to become exclusive',
        from: 'Tallassee',
        img: 'c-img',
        title: 'Ms Exotic looking for an older gentleman to bring light into your life',
        desc: ` I'm slim but curvaceous, ambitious,and soft-hearted lady with a tropical, exotic flair. Moonlight, delicious food and shiny things bring out the best in me. I am shy but enjoy engaging in intelligent conversations in business or politics. Something many can attest to, is the radiance and glow that often follow me. I am a force to be reckoned with, but emit only positivity--something I'd love to see in the world. I am ambitious and I need to be- I've got a world to change.I can't wait to meet my next benefactor.<br><br>I am seeking an older gentleman. Someone honest, direct, and generous. I'd like to meet someone who is wise, generous and willing to share his wisdom. Let's start with a glass of wine at an upscale restaurant to unwind your day.<br><br>Looking for generous gentlemen that are ages 45+ and looking to mentor a young lady on a dinner date`,
        note: `* Please include a picture and your age *`
    },
    {
        id: 9,
        vip: 0,
        age: 0,
        sex: 0,
        dt: 'Jan 29',
        short: 'In Full disclosure  I do have a small  package  ',
        from: 'Auburn',
        img: 'c-img',
        title: 'Ms Exotic looking for an older gentleman to bring light into your life',
        desc: ` I'm slim but curvaceous, ambitious,and soft-hearted lady with a tropical, exotic flair. Moonlight, delicious food and shiny things bring out the best in me. I am shy but enjoy engaging in intelligent conversations in business or politics. Something many can attest to, is the radiance and glow that often follow me. I am a force to be reckoned with, but emit only positivity--something I'd love to see in the world. I am ambitious and I need to be- I've got a world to change.I can't wait to meet my next benefactor.<br><br>I am seeking an older gentleman. Someone honest, direct, and generous. I'd like to meet someone who is wise, generous and willing to share his wisdom. Let's start with a glass of wine at an upscale restaurant to unwind your day.<br><br>Looking for generous gentlemen that are ages 45+ and looking to mentor a young lady on a dinner date`,
        note: `* Please include a picture and your age *`
    },
    {
        id: 10,
        vip: 0,
        age: 0,
        sex: 0,
        dt: 'Jan 29',
        short: 'Lookin for wifey..?  No bs',
        from: '',
        img: 'c-img',
        title: 'Ms Exotic looking for an older gentleman to bring light into your life',
        desc: ` I'm slim but curvaceous, ambitious,and soft-hearted lady with a tropical, exotic flair. Moonlight, delicious food and shiny things bring out the best in me. I am shy but enjoy engaging in intelligent conversations in business or politics. Something many can attest to, is the radiance and glow that often follow me. I am a force to be reckoned with, but emit only positivity--something I'd love to see in the world. I am ambitious and I need to be- I've got a world to change.I can't wait to meet my next benefactor.<br><br>I am seeking an older gentleman. Someone honest, direct, and generous. I'd like to meet someone who is wise, generous and willing to share his wisdom. Let's start with a glass of wine at an upscale restaurant to unwind your day.<br><br>Looking for generous gentlemen that are ages 45+ and looking to mentor a young lady on a dinner date`,
        note: `* Please include a picture and your age *`
    },
    {
        id: 11,
        vip: 0,
        age: 0,
        sex: 0,
        dt: 'Jan 29',
        short: '21 year old lunatic  hahahhaaha  seeking flame',
        from: 'AUBURN',
        img: 'c-img',
        title: 'Ms Exotic looking for an older gentleman to bring light into your life',
        desc: ` I'm slim but curvaceous, ambitious,and soft-hearted lady with a tropical, exotic flair. Moonlight, delicious food and shiny things bring out the best in me. I am shy but enjoy engaging in intelligent conversations in business or politics. Something many can attest to, is the radiance and glow that often follow me. I am a force to be reckoned with, but emit only positivity--something I'd love to see in the world. I am ambitious and I need to be- I've got a world to change.I can't wait to meet my next benefactor.<br><br>I am seeking an older gentleman. Someone honest, direct, and generous. I'd like to meet someone who is wise, generous and willing to share his wisdom. Let's start with a glass of wine at an upscale restaurant to unwind your day.<br><br>Looking for generous gentlemen that are ages 45+ and looking to mentor a young lady on a dinner date`,
        note: `* Please include a picture and your age *`
    },
    {
        id: 12,
        vip: 3,
        age: 0,
        sex: 0,
        dt: 'Jan 30',
        short: 'Amazing Kisses,  Butterflies and a new  home for my heart',
        from: '',
        img: 'c-img',
        title: 'Ms Exotic looking for an older gentleman to bring light into your life',
        desc: ` I'm slim but curvaceous, ambitious,and soft-hearted lady with a tropical, exotic flair. Moonlight, delicious food and shiny things bring out the best in me. I am shy but enjoy engaging in intelligent conversations in business or politics. Something many can attest to, is the radiance and glow that often follow me. I am a force to be reckoned with, but emit only positivity--something I'd love to see in the world. I am ambitious and I need to be- I've got a world to change.I can't wait to meet my next benefactor.<br><br>I am seeking an older gentleman. Someone honest, direct, and generous. I'd like to meet someone who is wise, generous and willing to share his wisdom. Let's start with a glass of wine at an upscale restaurant to unwind your day.<br><br>Looking for generous gentlemen that are ages 45+ and looking to mentor a young lady on a dinner date`,
        note: `* Please include a picture and your age *`
    }
]